### ISSUE TITLE
start with full bar in view

### ISSUE THREAD

**Issue by maidul98** [repodio/react-native-trimmer#15]
Hello, first off this component is amazing. Thank you for spending time making it.

I want to set it so that the full track is in view first and then the user can zoom in as they please. This might be simple but can't seem to find it. How would I set it so that the full length of the track is in view initially? Thank you!

**Comment by maidul98** [comment]
The answer is in the documentation

**Comment by jalexanderbryant** [comment]
@maidul98 How were you able to achieve this? I've tried using the documentation but with no luck.
