### ISSUE TITLE
Resize the trimmer ?

### ISSUE THREAD

**Issue by kicraft123** [repodio/react-native-trimmer#2]
Hello, it is possible to resize the trimmer with « width » or something else ? To fit to window or for giving a custom size ?

**Comment by CapitanRedBeard** [comment]
You could either wrap the `Trimmer` in a `View` and give that a set width. The `Trimmer` component works by being a horizontal scrollView so it generally needs to overflow off the screen. You can also zoom in far enough so the entire track is  on the screen and not overflowing.

Maybe throw up a little drawing of what you want to achieve and I can help you out.
